### ISSUE TITLE
any chance of RTSP address support?

### ISSUE THREAD

**Issue by jammmyb** [california444/homebridge-doorbell-telegram-photo#26]
i'm all setup, barring i haven't got any cameras that offer http:// they have RTSP streams.

is this something that could be incorporated in the future?

**Comment by ahmadnazirafiq** [comment]
Same. Tried other forms of URL still saying Pic not received. Any example for a working http:// URL format?

**Comment by california444** [comment]
HI, 

at the moment the plugin is not designed to support RTSP URLs for snapshots. 
For RTSP URLs to work, I guess the best option would be integrating ffmpeg to grab a picture from the live stream.
I can put RTSP support on the to do list, but I do not want to promise a date for this.
I will let you know once I have a first version to test...

Roman

**Comment by jammmyb** [comment]
The camera I’m using has still image feed. It’s a Hikvision one. It’s still RTSP and it’s what I enter in still image in homebridge. 

Would that be simpler to acquire than converting a stream?

RTSP would be key for most cameras to utilise this plugin. 👍

**Comment by california444** [comment]
I did a quick search and found that at least some Hikvision models support http URLs for still image. Maybe your model supports that as well? 
[https://www.google.com/search?client=safari&rls=en&q=rtsp+still+image+hikvision&ie=UTF-8&oe=UTF-8](https://www.google.com/search?client=safari&rls=en&q=rtsp+still+image+hikvision&ie=UTF-8&oe=UTF-8)

Nevertheless RTSP support would be good as soon as I have time for that....

**Comment by jammmyb** [comment]
Hi!

Thanks for active responses. i have spent the last hour googling still image, snapshot, et al. Its given me all sorts of addresses to try.

in the end, the snapshot that worked:
http://user:pass@ipaddress/ISAPI/Streaming/channels/101/picture

but now i get: 

> [8/22/2021, 10:42:53 AM] [DoorbellPhotoTelegram] Pic received
Unhandled rejection Error: ETELEGRAM: 400 Bad Request: chat not found
    at /homebridge/node_modules/homebridge-doorbell-telegram-photo/node_modules/node-telegram-bot-api/src/telegram.js:291:15
    at tryCatcher (/homebridge/node_modules/homebridge-doorbell-telegram-photo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/homebridge-doorbell-telegram-photo/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/homebridge/node_modules/homebridge-doorbell-telegram-photo/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/homebridge/node_modules/homebridge-doorbell-telegram-photo/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/homebridge/node_modules/homebridge-doorbell-telegram-photo/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/homebridge/node_modules/homebridge-doorbell-telegram-photo/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/homebridge/node_modules/homebridge-doorbell-telegram-photo/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/homebridge/node_modules/homebridge-doorbell-telegram-photo/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/homebridge/node_modules/homebridge-doorbell-telegram-photo/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:464:21)



![telegramdoorbell](https://user-images.githubusercontent.com/48286264/130350437-23601ba9-e6fd-4399-9a21-a289426bcb54.png)


i struggle with Telegram as it is [i managed somehow to get it to talk with unRAID and Tautulli.

any advice on the last bit please?

**Comment by california444** [comment]
Great to hear that http works for you.
My chatID starts with a minus sign. I guess that this is missing in your case as the log says that the Chat ID was not found. 

Roman

**Comment by jammmyb** [comment]
You diamond!

All working here! 👍👍👍

**Comment by california444** [comment]
Perfect! Then I will close this one.
